- agents/addon/extension/azure_tts/BUILD.gn
- agents/addon/extension/azure_tts/manifest.json
- agents/manifest.json.example
- agents/scripts/install_deps_and_build.sh
- Depends on azure_speech_sdk 1.38.0 rather than download latest
- Upgrade agora_rtc to 0.1.1 to leverage same azure_speech_sdk
> Depends on seperate azure_speech_sdk

- .gitignore
- Dockerfile
- Makefile
- agents/addon/extension/elevenlabs_tts/elevenlabs_tts.go
- agents/addon/extension/openai_chatgpt/manifest.json
- agents/addon/extension/openai_chatgpt/openai_chatgpt_extension.go
- agents/manifest.json.elevenlabs.example
- agents/manifest.json.example
- agents/scripts/package.sh
- server/internal/http_server.go
- server/main.go
1.support different TTS providers based on language selected
2.add max_memory_length configuration option for OpenAI ChatGPT extension
3.update Dockerfile and Makefile for improved build process
> support different TTS providers based on language selected

- .github/workflows/build-docker.yaml
- use git version with tag as docker tag 
- leverage github's var so that forked repos can publish to their registry as well
> Fix docker tag version

- .gitignore
- README.md
- astra-architecture.md
* Consistency change
* restructure modals and extension part
* Adding 11labs as option in the config part 
* Adding .next to gitignore
> Readme update

- agents/addon/extension/chat_transcriber_python/__init__.py
- agents/addon/extension/chat_transcriber_python/chat_transcriber_addon.py
- agents/addon/extension/chat_transcriber_python/chat_transcriber_extension.py
- agents/addon/extension/cosy_tts/__init__.py
- agents/addon/extension/cosy_tts/cosy_tts_addon.py
- agents/addon/extension/cosy_tts/cosy_tts_extension.py
- agents/addon/extension/elevenlabs_tts_python/__init__.py
- agents/addon/extension/elevenlabs_tts_python/elevenlabs_tts_addon.py
- agents/addon/extension/interrupt_detector_python/__init__.py
- agents/addon/extension/interrupt_detector_python/interrupt_detector_addon.py
- agents/addon/extension/interrupt_detector_python/interrupt_detector_extension.py
- agents/addon/extension/openai_chatgpt_python/__init__.py
- agents/addon/extension/openai_chatgpt_python/openai_chatgpt_addon.py
- agents/addon/extension/qwen_llm_python/__init__.py
- agents/addon/extension/qwen_llm_python/qwen_llm_addon.py
- agents/addon/extension/qwen_llm_python/qwen_llm_extension.py
Delay python dependencies being imported until the python extension is instantiated by 'on_create_instance'
> Reduce side effects of unused python extensions

- server/internal/worker.go
from #78 
----
kill -9 is not recommend, syscall.Kill SIGTERM instead of.
> Make worker kill better

- README.md
cp: './agents/manifest.json.elevenlabs.example' and './agents/manifest.json.elevenlabs.example' are the same file
> Update README.md - Rename manifest example

- .github/workflows/build-docker.yaml
`ghcr.io/rte-design/astra_playground` image will be built and published automatically for main branch as well as release tags.
> Build playground docker image automatically 

- agents/scripts/build/main.go
- agents/scripts/install_deps_and_build.sh
Example of error message:
```text
02:30:12 Error: auto detect extensions failed. Root cause: 
the extensions [elevenlabs_tts] and [interrupt_detector] have duplicated module name [extension]
exit status 1
FATAL: failed to build go app, see logs for detail.
make: *** [Makefile:11: build-agents] Error 1
```
> Fix: check if go extensions have duplicated go module name

- README.md
- docs/readmes/README-CN.md
- docs/readmes/README-JP.md
I created Japanese translated README.
> docs: add Japanese README

- docs/readmes/README-CN.md
- docs/readmes/README-JP.md
- docs/readmes/README-KR.md
plz check the quick links work or not
thanks!
> Add Korean version

- README.md
- docs/readmes/README-CN.md
- playground/src/platform/pc/description/index.tsx
* Adding back the banner image 
* Changed the link of Gitbook to doc.theten.ai
* Adding the comparison table 
* Update the X account
> readme change and astra multimodal agent update

- agents/scripts/install_deps_and_build.sh
- server/internal/http_server.go
- server/internal/worker.go
- server/main.go
2. ensure all processes are killed when SIG_TERM is received
> 1. pre-import llama-index package

- agents/property.json
- agents/property.json.example
- agents/ten_packages/extension/gemini_llm_python/gemini_llm.py
- agents/ten_packages/extension/gemini_llm_python/gemini_llm_extension.py
1.fix prompt and attribute settings for gemini LLM
> fix(): fix prompt and attribute settings

- playground/src/common/constant.ts
- playground/src/common/graph.ts
- playground/src/types/index.ts
https://github.com/TEN-framework/ASTRA.ai/issues/171
> feat: support korean and japanese

- .devcontainer/devcontainer.json
- .vscode/launch.json
- .vscode/tasks.json
- agents/main.go
- agents/manifest-lock.json
- agents/manifest.json
- agents/property.json
- agents/scripts/install_deps_and_build.sh
- agents/ten_packages/extension/aliyun_analyticdb_vector_storage/manifest.json
- agents/ten_packages/extension/aliyun_text_embedding/manifest.json
- agents/ten_packages/extension/azure_tts/manifest.json
- agents/ten_packages/extension/bedrock_llm_python/manifest.json
- agents/ten_packages/extension/chat_transcriber/manifest.json
- agents/ten_packages/extension/chat_transcriber_python/manifest.json
- agents/ten_packages/extension/cosy_tts/manifest.json
- agents/ten_packages/extension/elevenlabs_tts/manifest.json
- agents/ten_packages/extension/elevenlabs_tts_python/manifest.json
- agents/ten_packages/extension/file_chunker/manifest.json
- agents/ten_packages/extension/gemini_llm_python/manifest.json
- agents/ten_packages/extension/http_server_python/manifest.json
- agents/ten_packages/extension/interrupt_detector/manifest.json
- agents/ten_packages/extension/interrupt_detector_python/manifest.json
- agents/ten_packages/extension/llama_index_chat_engine/manifest.json
- agents/ten_packages/extension/message_collector/manifest.json
- agents/ten_packages/extension/openai_chatgpt/manifest.json
- agents/ten_packages/extension/openai_chatgpt_python/manifest.json
- agents/ten_packages/extension/polly_tts/manifest.json
- agents/ten_packages/extension/qwen_llm_python/manifest.json
- agents/ten_packages/extension/transcribe_asr_python/manifest.json
- Upgrade TEN runtimes to `0.2`, build image to `0.5.2`
- Able to debug `go/python/cpp` **individually** via launch (refer to https://doc.theten.ai/ten-framework/debugging for more details as well as advanced usage)
- set `BUILD_TYPE=debug` in `agents/scripts/install_deps_and_build.sh` for cpp debugging
> Add basic debugging support

- playground/src/app/layout.tsx
- playground/src/components/loginCard/index.tsx
- playground/src/platform/pc/description/index.tsx
* changing the text "realtime" to "real-time" to keep the consistency.
> fix: wording fix

- playground/src/components/loginCard/index.module.scss
- playground/src/components/loginCard/index.tsx
When the login page is loaded, clicking join will not respond and the loading text will be displayed #297
> feat: improve first time loading experience, only enable Join button until it's fully functional

- README.md
* Adding the OpenAI Realtime API part 
* A couple of small consistency fix 
* Getting rid of docker setting gif, too many gifs might make your feel overwhelming.
> docs: updating OpenAI Realtime API part to the README.md

- agents/ten_packages/extension/openai_v2v_python/conf.py
* changing the case of Ten Agent in basic prompt
> fix: one liner changing the case of the Ten Agent

- demo/src/app/api/agents/start/graph.tsx
* updating greetings for different models.
> fix: updating the greetings for different models.

- demo/src/app/layout.tsx
- demo/src/app/page.tsx
- demo/src/components/loginCard/index.module.scss
- demo/src/components/loginCard/index.tsx
- demo/src/platform/pc/description/index.tsx
* Adding a loading state of Join btn
> fix: adding the loading state for the Join btn on the landing page.

- README.md
> docs: updating wording and adding new gif

- README.md
> docs: updating the readme

- docs/readmes/README-CN.md
> docs: updating CN readme

- agents/ten_packages/extension/deepgram_asr_python/requirements.txt
fix deepgram websocket error, https://github.com/deepgram/deepgram-python-sdk/issues/483
> fix deepgram websocket error

- README.md
adding git global setting to handle line endings
> docs: adding git global setting to handle line endings

- README.md
adding usecases section and moving star us section down
> docs: adding usecases section and moving star us section down

- agents/ten_packages/extension/bingsearch_tool_python/extension.py
```
[agora_yde] 2024-11-21 16:21:21,493 - openai_v2v_python - INFO - 27637 - [extension.py:380] - append item {'id': 'item_AW4DgJBUU90q5QBQaQMeQ', 'object': 'realtime.item', 'type': 'function_call', 'status': 'completed', 'name': 'bing_search', 'call_id': 'call_bvB5RUNoyydCup88', 'arguments': '{"query":"2024 美国总统选举结果"}'}
[agora_yde] 2024-11-21 16:21:21,493 - openai_v2v_python - INFO - 27637 - [extension.py:384] - remove history item_AW4COffmXDIvNH6XmI7Hz
[agora_yde] 11-21 16:21:21.510 27637(27792) W on_cmd@llm_tool.py:58 [bingsearch_tool_python] on_cmd failed: Traceback (most recent call last):
[agora_yde]   File "/app/agents/ten_packages/system/ten_ai_base/interface/ten_ai_base/llm_tool.py", line 46, in on_cmd
[agora_yde]     result = await asyncio.create_task(self.run_tool(ten_env, …
```
> fix http session closed error

- docker-compose.yml
- playground/src/common/hooks.ts
- playground/src/common/moduleConfig.ts
- playground/src/components/Chat/ChatCfgModuleSelect.tsx
To further enhance module management, solves following issue:
- all addons should have a label for easy readiness
- different llm/v2v extension support different tool set
- only registered modules should i appear, and its type should follow registry configs instead of addon name
> feat: better module registry

- agents/ten_packages/extension/cartesia_tts/tests/test_basic.py
- agents/ten_packages/extension/cosy_tts_python/tests/test_basic.py
- agents/ten_packages/extension/dify_python/tests/test_basic.py
- agents/ten_packages/extension/elevenlabs_tts_python/tests/test_basic.py
- agents/ten_packages/extension/file_chunker/file_chunker_extension.py
- agents/ten_packages/extension/glue_python_async/tests/test_basic.py
- agents/ten_packages/extension/http_server_python/http_server_extension.py
- agents/ten_packages/extension/interrupt_detector_python/extension.py
- agents/ten_packages/extension/llama_index_chat_engine/llama_embedding.py
- agents/ten_packages/extension/llama_index_chat_engine/llama_llm.py
- agents/ten_packages/extension/llama_index_chat_engine/llama_retriever.py
- agents/ten_packages/extension/minimax_tts_python/tests/test_basic.py
- agents/ten_packages/extension/qwen_llm_python/qwen_llm_extension.py
- agents/ten_packages/extension/vision_analyze_tool_python/tests/test_basic.py
- agents/ten_packages/extension/vision_tool_python/tests/test_basic.py
This pull request introduces a consistent change across multiple files to update lambda function signatures. The change adds an unused third parameter to the lambda functions used in `send_cmd` calls.
The most important changes include:
Updates to lambda function signatures:
* [`agents/ten_packages/extension/cartesia_tts/tests/test_basic.py`](diffhunk://#diff-ca74f9d60e0dab97e6d5d42d931d890e15cdbfdd3db39201e3a3cda83543f7bfL25-R25): Modified lambda function in `on_start` to include an unused third parameter.
* [`agents/ten_packages/extension/file_chunker/file_chunker_extension.py`](diffhunk://#diff-2640e3df0782d6bc8e28706c29ab14a24d3b4238191dcf2718377567c1ab3648L87-R87): Updated lambda functions in `create_collection`, `embedding`, `vector_store`, and `file_chunked` to include an unused …
> fix: update lambda functions to include unused parameter

- agents/examples/experimental/property.json
Same graph as voice assistance but without interrupt node, redirecting STT output to LLM without interrupt in between for use-case such as transcription where previous LLM output data should not be dropped in case of new Input.
> experimental voice assistance without user interrupt to LLM response
