agents/addon/extension/elevenlabs_tts/elevenlabs_tts_extension.go, agents/addon/extension/elevenlabs_tts/manifest.json, agents/addon/extension/elevenlabs_tts/pcm.go
1.optimize pcm logic
2.stat latency
=> [Feature Request] Feat tts elevenlabs

.devcontainer/devcontainer.json
so that easier to contribute from devcontainer/codespaces.
=> Add git for devcontainer

agents/addon/extension/cosy_tts/main.py, agents/addon/extension/qwen_llm_python/main.py, agents/manifest.json.qwen.example
* fix cosy interrupt and safe exit
* fix init
=> Dev/fix cosy bug (#105)

agents/scripts/install_deps_and_build.sh
Closes https://github.com/rte-design/ASTRA.ai/issues/134
=> Report error on unspported platform

agents/addon/extension/cosy_tts/cosy_tts_extension.py
Otherwise cozy TTS may cache some sentences until more comes in.
=> Fix cozy tts no response

agents/scripts/install_deps_and_build.sh
related to https://github.com/rte-design/ASTRA.ai/pull/143
=> Fix check not work on orbstack

docs/readmes/README-CN.md, docs/readmes/README-JP.md, docs/readmes/README-KR.md, playground/package.json
• Adding Astra banner image for all READMEs.
• 030 - 040 in `playground/package.json`.
=> Consistency change

agents/manifest-lock.json, agents/manifest.json
- remove unnecessary so to be smaller
=> Upgrade agora_rtc to 0.5.1

README.md, docs/readmes/README-JP.md
* updating readme japanese
* fixing the issue closed badge
=> docs: updating readme-japanese also fixed the issue closed badge

agents/scripts/.gitignore, agents/scripts/dot.py
A simple script to generate a nice graph, currently it only generate the first one, but it could be improved easily.
=> feat: add a script to generate a nice graph

docs/readmes/README-CN.md, docs/readmes/README-ES.md, docs/readmes/README-FR.md, docs/readmes/README-IT.md, docs/readmes/README-KR.md
* update cn es and fr versioned readme based the default version
=> Docs: updating READMEs in other languages.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/custom.md
=> docs: updating issue templates

demo/src/app/api/agents/start/graph.tsx
Correcting the voices of male and female
=> fix: correcting the male and female voice

demo/src/app/index.module.scss
This pull request addresses issue #109, where the background image disappears when the screen size is large. The CSS has been updated to improve the visibility and responsiveness of the background image.
=> Fix background image disappearing on large screens

docs/readmes/README-CN.md
=> docs: Updating README-CN.md

.github/workflows/build-docker.yaml
=> fix: allow non-v tags to trigger ci

agents/scripts/install_deps_and_build.sh
The `liblinux_audio_hy_extension.so` is useful in some scenario.
=> fix: don't delete useful lib

playground/README.md, playground/src/app/layout.tsx, playground/src/components/Chat/ChatCfgSelect.tsx
Refer to  [BUG] playground property override is not showing values property sometimes #432 
Scope
- Playground
Fix
=> fix(playground): cfg settings

agents/examples/experimental/property.json
One liner fixing type of deepgram sample rate
=> fix: one liner fixing type of deepgram sample rate

README.md
=> docs: updating diagram image

.gitattributes, README.md, docs/readmes/README-CN.md, docs/troubleshooting/troubleshooting-cn.md
=> docs: updating readme

Dockerfile, Taskfile.yml, agents/examples/demo/property.json
1.use agents/examples/demo for building agents
2.add the graph va_coze_azure to agents/examples/demo
=> fix(): use agents/examples/demo for building agents

demo/src/app/layout.tsx, demo/src/common/constant.ts, demo/src/components/Card/Login.tsx, demo/src/components/Layout/Action.tsx, playground/src/components/Layout/Action.tsx
=> feat: wording change

demo/package.json, demo/pnpm-lock.yaml, demo/src/app/layout.tsx, demo/src/common/constant.ts, demo/src/components/Icon/index.tsx, demo/src/components/Layout/Header.tsx, demo/src/components/Layout/HeaderComponents.tsx, demo/src/hooks/index.ts, demo/src/lib/utils.ts, demo/tailwind.config.js
extends https://github.com/TEN-framework/TEN-Agent/pull/461
=> fix(demo): header components

agents/ten_packages/extension/gemini_v2v_python/BUILD.gn, agents/ten_packages/extension/gemini_v2v_python/README.md, agents/ten_packages/extension/gemini_v2v_python/__init__.py, agents/ten_packages/extension/gemini_v2v_python/addon.py, agents/ten_packages/extension/gemini_v2v_python/extension.py, agents/ten_packages/extension/gemini_v2v_python/manifest.json, agents/ten_packages/extension/gemini_v2v_python/property.json, agents/ten_packages/extension/gemini_v2v_python/requirements.txt, agents/ten_packages/extension/openai_v2v_python/property.json, docker-compose.yml, playground/src/common/graph.ts, playground/src/common/hooks.ts, playground/src/common/moduleConfig.ts, playground/src/components/Chat/ChatCfgModuleSelect.tsx, playground/src/components/ui/dropdown.tsx, playground/src/store/reducers/global.ts
=> feat: support gemini v2v

demo/Dockerfile, demo/package.json, playground/Dockerfile, playground/package.json
- fixed issue in https://github.com/TEN-framework/TEN-Agent/actions/runs/13149944768/job/36695498077
=> fix: fix docker

.github/workflows/build-docker.yaml, playground/Dockerfile
- Support non-edit mode for playground image
=> feat: support build flags for non-edit mode

agents/examples/default/manifest.json, agents/examples/demo/manifest.json, agents/examples/experimental/manifest.json, agents/ten_packages/extension/bedrock_llm_python/extension.py, agents/ten_packages/extension/bingsearch_tool_python/extension.py, agents/ten_packages/extension/coze_python_async/extension.py, agents/ten_packages/extension/dify_python/extension.py, agents/ten_packages/extension/gemini_v2v_python/extension.py, agents/ten_packages/extension/glue_python_async/extension.py, agents/ten_packages/extension/openai_chatgpt_python/extension.py, agents/ten_packages/extension/openai_image_generate_tool/extension.py, agents/ten_packages/extension/openai_v2v_python/extension.py, agents/ten_packages/extension/vision_analyze_tool_python/extension.py, agents/ten_packages/extension/vision_tool_python/extension.py, agents/ten_packages/extension/weatherapi_tool_python/extension.py
- https://github.com/TEN-framework/TEN-Agent/issues/581
=> fix: fix all potential circular imports

docs/readmes/README-CN.md, docs/readmes/README-ES.md, docs/readmes/README-FR.md, docs/readmes/README-IT.md, docs/readmes/README-JP.md, docs/readmes/README-KR.md
Translated six languages according to README.md, and added WeChat and goproxy to Chinese
=> Translate 6 Nations README.md

docs/readmes/README-CN.md, docs/readmes/README-ES.md, docs/readmes/README-FR.md, docs/readmes/README-IT.md, docs/readmes/README-JP.md, docs/readmes/README-KR.md
National user api registration
=> README-CN Agora API Registration

agents/ten_packages/extension/bytedance_asr/bytedance_asr.py, agents/ten_packages/extension/bytedance_asr/requirements.txt, agents/ten_packages/extension/bytedance_tts/bytedance_tts.py, agents/ten_packages/extension/bytedance_tts/requirements.txt, agents/ten_packages/extension/cartesia_tts/cartesia_tts.py, agents/ten_packages/extension/deepgram_asr_python/requirements.txt, agents/ten_packages/extension/fashionai/requirements.txt, agents/ten_packages/extension/neuphonic_tts/requirements.txt
Closes https://github.com/TEN-framework/TEN-Agent/issues/611
=> feat: upgrade websockets>=14.0

README.md
- Change icons for "Run Agent Demo" and "Deploying with Docker" for better visual representation.
- Refine community engagement section with updated follower counts and improved link formatting.
- Enhance description of TEN's integration with Coze platform for clarity.
- Minor formatting adjustments for better readability.
=> Update README.md for improved clarity and consistency

README.md
- Change the "🤝 Contributing" section icon to "🥰" for a more inviting tone.
- Refine the description of the TEN Agent architecture, adding details about the core application, development server, and front-end UI ports.
- Improve the contributing section with a welcoming message and links to maintainers for better community interaction.
=> Update README.md to enhance clarity and engagement

docs/readmes/README-ES.md
Closes #671 
Updated the READEME-ES.md to match the current version of README.md
Added table of content
Updated headings
Updated Links
Added missing sections
=> docs: Update README-ES.md to match current README.md

.github/workflows/ai_agents.yaml, .github/workflows/build_docker_for_ai_agents.yml, core/src/ten_manager/designer_frontend/src/api/endpoints/index.ts, core/src/ten_manager/designer_frontend/src/api/endpoints/messages.ts, core/src/ten_manager/designer_frontend/src/api/services/extension.ts, core/src/ten_manager/designer_frontend/src/api/services/messages.ts, core/src/ten_manager/designer_frontend/src/components/Popup/Graph.tsx, core/src/ten_manager/designer_frontend/src/components/Widget/GraphsWidget.tsx, core/src/ten_manager/designer_frontend/src/flow/ContextMenu/NodeContextMenu.tsx, core/src/ten_manager/designer_frontend/src/types/graphs.ts, core/src/ten_manager/designer_frontend/src/types/widgets.ts
- support compatible API
- refactor connection creation widget
=> feat: compatible connection
